# Generated by Django 4.2.1 on 2023-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_subjects_sem_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='university_marks',
            field=models.FloatField(default=0),
        ),
    ]
