# Generated by Django 4.2.1 on 2023-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_studentresult_university_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='university_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='sem_no',
            field=models.IntegerField(default=0),
        ),
    ]
