# Generated by Django 4.2.1 on 2023-06-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_universitymarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityMarks',
        ),
    ]
